# config/agent_config.yaml - ZERO DELAY CONFIGURATION
# EDR Agent ZERO DELAY Configuration - Immediate Data Transmission

# ============================================================================
# AGENT CORE CONFIGURATION - ZERO DELAY OPTIMIZED
# ============================================================================
agent:
  name: "EDR-SecurityAgent-ZeroDelay"
  version: "2.0.0-ZeroDelay"
  environment: "production"
  
  # ZERO DELAY: Immediate transmission settings
  immediate_transmission: true           # NEW: Enable immediate transmission
  zero_delay_mode: true                 # NEW: Enable zero delay processing
  
  # Heartbeat and Communication - ZERO DELAY OPTIMIZED
  heartbeat_interval: 10                # REDUCED: From 45 to 10 seconds for immediate feedback
  heartbeat_timeout: 30                 # REDUCED: From 120 to 30 seconds
  max_heartbeat_failures: 2             # REDUCED: Faster failure detection
  
  # Event Processing - ZERO DELAY OPTIMIZED
  event_batch_size: 1                   # ZERO DELAY: Send one event immediately
  event_queue_size: 10                  # ZERO DELAY: Minimal queue for immediate processing
  max_memory_usage: 256                 # REDUCED: Minimal memory for immediate processing
  
  # Performance Settings - ZERO DELAY OPTIMIZED
  max_cpu_usage: 25                     # INCREASED: Allow more CPU for immediate processing
  auto_throttle: false                  # DISABLED: No throttling for immediate response
  adaptive_polling: false               # DISABLED: Fixed minimal polling for consistency
  
  # ZERO DELAY: Processing configuration
  immediate_processing: true            # NEW: Enable immediate event processing
  immediate_send_threshold_ms: 1        # NEW: Send within 1 millisecond
  minimal_polling_interval_ms: 1        # NEW: 1ms polling for immediate detection
  
  # ZERO DELAY: Communication optimization
  connection_pool_size: 20              # NEW: More connections for immediate requests
  keep_alive_timeout: 30                # NEW: Keep connections alive
  request_timeout: 2                    # NEW: Fast request timeout
  immediate_retry_disabled: true        # NEW: No retries for immediate processing

# ============================================================================
# SERVER CONNECTION CONFIGURATION - ZERO DELAY OPTIMIZED
# ============================================================================
server:
  # Primary Server
  host: "192.168.20.85"
  port: 5000
  protocol: "http"
  base_url: "http://192.168.20.85:5000"
  
  # Authentication
  auth_token: "edr_agent_auth_2024"
  
  # ZERO DELAY: Connection Settings
  timeout: 2                            # ZERO DELAY: Very fast timeout
  connect_timeout: 1                    # ZERO DELAY: Fast connection timeout
  read_timeout: 1                       # ZERO DELAY: Fast read timeout
  max_retries: 0                        # ZERO DELAY: No retries for immediate processing
  retry_delay: 0                        # ZERO DELAY: No retry delay
  
  # ZERO DELAY: Connection optimization
  keep_alive: true                      # Keep connections alive
  connection_pool_size: 20              # More connections for immediate processing
  pool_maxsize: 20                      # Maximum pool size
  pool_block: false                     # Don't block on pool exhaustion
  
  # SSL/TLS Settings
  ssl_enabled: false
  ssl_verify: false                     # DISABLED: Skip SSL verification for speed

# ============================================================================
# DATA COLLECTION CONFIGURATION - ZERO DELAY OPTIMIZED
# ============================================================================
collection:
  enabled: true
  
  # ZERO DELAY: Global Collection Settings
  real_time_monitoring: true
  immediate_processing: true            # NEW: Enable immediate processing
  zero_delay_enabled: true              # NEW: Enable zero delay mode
  polling_interval: 0.001               # ZERO DELAY: 1ms polling interval
  max_events_per_interval: 1            # ZERO DELAY: One event at a time
  event_deduplication: false            # DISABLED: No deduplication for immediate processing
  
  # Event Types - All enabled for immediate monitoring
  collect_processes: true
  collect_files: true
  collect_network: true
  collect_registry: true
  collect_authentication: true
  collect_system_events: true
  
  # ZERO DELAY: Process Monitoring
  process_monitoring:
    immediate_detection: true           # NEW: Immediate process detection
    polling_interval_ms: 1              # NEW: 1ms polling
    monitor_creation: true
    monitor_termination: true
    monitor_modification: true
    collect_command_lines: true
    collect_hashes: false               # DISABLED: Skip expensive operations
    monitor_child_processes: true
  
  # ZERO DELAY: File Monitoring
  file_monitoring:
    enabled: true
    immediate_detection: true           # NEW: Immediate file detection
    polling_interval_ms: 1              # NEW: 1ms polling
    paths_to_monitor:
      - "C:\\Users\\manhh\\Desktop"
      - "C:\\Users\\manhh\\Documents"
      - "C:\\Users\\manhh\\Downloads"
    file_extensions:
      - ".exe"
      - ".dll"
      - ".bat"
      - ".cmd"
      - ".ps1"
    max_file_size: 10MB                 # REDUCED: Smaller files for immediate processing
    collect_hashes: false               # DISABLED: Skip expensive operations
    monitor_creation: true
    monitor_modification: true
    monitor_deletion: true
    monitor_access: false               # DISABLED: Reduce noise for immediate processing
  
  # ZERO DELAY: Network Monitoring
  network_monitoring:
    immediate_detection: true           # NEW: Immediate network detection
    polling_interval_ms: 1              # NEW: 1ms polling
    monitor_tcp: true
    monitor_udp: false                  # DISABLED: Reduce noise
    monitor_listening_ports: true
    monitor_established_connections: true
    monitor_outbound_only: true
    analyze_patterns: false             # DISABLED: Skip analysis for immediate processing
    max_connections_tracked: 100        # REDUCED: Smaller tracking for immediate processing
  
  # ZERO DELAY: Registry Monitoring
  registry_monitoring:
    immediate_detection: true           # NEW: Immediate registry detection
    polling_interval_ms: 10             # NEW: 10ms polling (registry is slower)
    monitor_startup_keys: true
    real_time_monitoring: true
    critical_paths:
      - "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run"
      - "HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run"
  
  # ZERO DELAY: Authentication Monitoring
  authentication_monitoring:
    immediate_detection: true           # NEW: Immediate auth detection
    polling_interval_ms: 100            # NEW: 100ms polling (auth events are less frequent)
    monitor_logons: true
    monitor_failed_attempts: true
    failed_attempt_threshold: 3         # REDUCED: Lower threshold for immediate alerting
  
  # ZERO DELAY: System Monitoring
  system_monitoring:
    immediate_detection: true           # NEW: Immediate system detection
    polling_interval_ms: 10             # NEW: 10ms polling
    monitor_cpu_usage: true
    monitor_memory_usage: true
    monitor_performance: true
    cpu_threshold: 90                   # INCREASED: Higher threshold to reduce noise
    memory_threshold: 90                # INCREASED: Higher threshold to reduce noise

# ============================================================================
# THREAT DETECTION CONFIGURATION - ZERO DELAY OPTIMIZED
# ============================================================================
detection:
  enabled: true
  immediate_detection: true             # NEW: Immediate threat detection
  
  # ZERO DELAY: Detection Engines
  local_rules_enabled: true
  behavioral_analysis: false           # DISABLED: Skip slow analysis
  threat_intelligence: false          # DISABLED: Skip slow lookups
  
  # ZERO DELAY: Detection Thresholds
  suspicious_threshold: 80             # INCREASED: Higher threshold for immediate alerts
  malicious_threshold: 90              # INCREASED: Higher threshold for immediate alerts
  alert_threshold: 85                  # INCREASED: Higher threshold for immediate alerts
  
  # ZERO DELAY: Response Actions
  send_alerts_immediately: true        # NEW: Send alerts immediately
  immediate_response: true             # NEW: Immediate response actions

# ============================================================================
# LOGGING CONFIGURATION - ZERO DELAY OPTIMIZED
# ============================================================================
logging:
  level: "INFO"
  
  # Output Destinations
  console_enabled: true
  file_enabled: true
  
  # ZERO DELAY: File Logging
  log_directory: "logs"
  log_file_name: "edr_agent_zero_delay.log"
  max_file_size: "5MB"                 # REDUCED: Smaller files for immediate processing
  backup_count: 2                      # REDUCED: Fewer backups for immediate processing
  
  # ZERO DELAY: Log Settings
  log_format: "simple"                 # Simple format for immediate logging
  include_timestamps: true
  include_thread_info: false           # DISABLED: Reduce logging overhead
  
  # ZERO DELAY: Component-specific Logging
  collectors_log_level: "INFO"
  communication_log_level: "INFO"
  detection_log_level: "INFO"
  immediate_processing_log_level: "DEBUG"  # NEW: Debug immediate processing

# ============================================================================
# PERFORMANCE OPTIMIZATION - ZERO DELAY OPTIMIZED
# ============================================================================
performance:
  # ZERO DELAY: CPU Management
  max_cpu_usage: 30                    # INCREASED: Allow more CPU for immediate processing
  cpu_throttling: false                # DISABLED: No throttling for immediate response
  priority_class: "high"               # INCREASED: High priority for immediate processing
  
  # ZERO DELAY: Memory Management
  max_memory_usage: 256                # REDUCED: Minimal memory for immediate processing
  memory_optimization: true
  garbage_collection: false           # DISABLED: Skip GC for immediate processing
  
  # ZERO DELAY: I/O Optimization
  async_processing: true
  batch_processing: false             # DISABLED: No batching for immediate processing
  compression_enabled: false         # DISABLED: Skip compression for speed
  buffer_size: 1024                  # REDUCED: Minimal buffer for immediate processing
  
  # ZERO DELAY: Threading
  max_worker_threads: 8               # INCREASED: More threads for immediate processing
  thread_pool_size: 8                # INCREASED: Larger pool for immediate processing
  async_event_processing: true
  
  # ZERO DELAY: Caching
  enable_caching: false               # DISABLED: No caching for immediate processing
  immediate_mode_optimizations: true  # NEW: Enable immediate mode optimizations

# ============================================================================
# FILTERING CONFIGURATION - ZERO DELAY OPTIMIZED
# ============================================================================
filters:
  # ZERO DELAY: Minimal Filtering for immediate processing
  exclude_system_processes: false     # DISABLED: Monitor everything for immediate detection
  exclude_agent_activity: true
  
  # ZERO DELAY: Process Filtering - Minimal exclusions
  exclude_process_names: []           # EMPTY: Monitor all processes for immediate detection
  exclude_process_paths: []           # EMPTY: Monitor all paths for immediate detection
  
  # ZERO DELAY: File Filtering - Minimal exclusions
  exclude_file_extensions: []         # EMPTY: Monitor all files for immediate detection
  exclude_file_paths: []              # EMPTY: Monitor all paths for immediate detection
  
  # ZERO DELAY: Network Filtering - Minimal exclusions
  exclude_loopback: false             # DISABLED: Monitor everything for immediate detection
  exclude_ports: []                   # EMPTY: Monitor all ports for immediate detection
  
  # ZERO DELAY: Size Limits - Minimal limits
  max_file_size_mb: 50                # REDUCED: Smaller files for immediate processing
  max_command_line_length: 1024       # INCREASED: Allow longer command lines
  max_registry_value_size: 512        # INCREASED: Allow larger registry values

# ============================================================================
# ALERTING CONFIGURATION - ZERO DELAY OPTIMIZED
# ============================================================================
alerting:
  enabled: true
  immediate_alerting: true             # NEW: Enable immediate alerting
  
  # ZERO DELAY: Alert Levels - All enabled for immediate alerting
  send_info_alerts: true              # ENABLED: Send all alerts immediately
  send_low_alerts: true               # ENABLED: Send all alerts immediately
  send_medium_alerts: true            # ENABLED: Send all alerts immediately
  send_high_alerts: true
  send_critical_alerts: true
  
  # ZERO DELAY: Alert Throttling - Minimal throttling
  throttle_duplicate_alerts: false    # DISABLED: No throttling for immediate alerting
  duplicate_window: 0                 # ZERO DELAY: No duplicate window
  max_alerts_per_minute: 1000         # INCREASED: Allow more alerts for immediate processing
  
  # ZERO DELAY: Alert Delivery
  immediate_delivery: true            # ENABLED: Immediate alert delivery
  batch_delivery: false              # DISABLED: No batching for immediate alerting
  batch_interval: 0                  # ZERO DELAY: No batch interval

# ============================================================================
# SECURITY NOTIFICATION CONFIGURATION - ZERO DELAY OPTIMIZED
# ============================================================================
security_notifications:
  enabled: true
  immediate_notifications: true       # NEW: Enable immediate notifications
  
  # ZERO DELAY: Display Settings
  show_on_screen: true
  position: "bottom-right"
  
  # ZERO DELAY: Alert Filtering - All enabled for immediate alerting
  show_low_alerts: true               # ENABLED: Show all alerts immediately
  show_medium_alerts: true            # ENABLED: Show all alerts immediately
  show_high_alerts: true
  show_critical_alerts: true
  
  # ZERO DELAY: Notification Behavior
  auto_dismiss_timeout: 10            # REDUCED: Faster dismissal for immediate processing
  play_sound: true                    # ENABLED: Audio alerts for immediate notification
  persistent_critical: true
  
  # ZERO DELAY: Rate Limiting - Minimal limiting
  max_security_alerts_per_minute: 100 # INCREASED: Allow more alerts for immediate processing
  duplicate_suppression_window: 0     # ZERO DELAY: No suppression window
  
  # ZERO DELAY: Priority-based Timeouts
  critical_alert_timeout: 30          # REDUCED: Faster timeout for immediate processing
  high_alert_timeout: 20              # REDUCED: Faster timeout for immediate processing
  medium_alert_timeout: 15            # REDUCED: Faster timeout for immediate processing
  low_alert_timeout: 10               # REDUCED: Faster timeout for immediate processing
  
  # ZERO DELAY: Content Settings
  include_rule_name: true
  include_risk_score: true
  include_event_details: true         # ENABLED: Full details for immediate alerts
  max_description_length: 500         # INCREASED: More details for immediate alerts
  
  # ZERO DELAY: Advanced Features
  group_similar_alerts: false         # DISABLED: No grouping for immediate alerts
  escalation_enabled: true            # ENABLED: Immediate escalation
  integration_mode: "immediate"       # NEW: Immediate integration mode

# ============================================================================
# MAINTENANCE AND UPDATES - ZERO DELAY OPTIMIZED
# ============================================================================
maintenance:
  # ZERO DELAY: Automatic Updates
  auto_update_enabled: false          # DISABLED: No updates during immediate processing
  
  # ZERO DELAY: Cleanup Tasks
  cleanup_enabled: false              # DISABLED: No cleanup during immediate processing
  
  # ZERO DELAY: Data Retention
  event_retention_days: 1             # REDUCED: Minimal retention for immediate processing
  log_retention_days: 7               # REDUCED: Minimal retention for immediate processing
  
  # ZERO DELAY: Health Monitoring
  health_check_interval: 10           # REDUCED: Frequent health checks for immediate processing
  send_health_reports: true           # ENABLED: Immediate health reporting

# ============================================================================
# ZERO DELAY SPECIFIC CONFIGURATION
# ============================================================================
zero_delay:
  # Core Settings
  enabled: true                       # Enable ZERO DELAY mode
  mode: "immediate"                   # Immediate processing mode
  
  # Performance Settings
  immediate_send_threshold_ms: 1      # Send within 1 millisecond
  minimal_polling_interval_ms: 1     # 1ms polling interval
  immediate_queue_size: 1             # Minimal queue size
  
  # Network Settings
  immediate_connection_pool: 20       # Connection pool for immediate requests
  immediate_timeout_ms: 2000          # 2 second timeout for immediate requests
  immediate_retry_disabled: true     # No retries for immediate processing
  
  # Processing Settings
  skip_expensive_operations: true    # Skip hash calculations, etc.
  prioritize_speed: true             # Prioritize speed over accuracy
  minimal_validation: true           # Minimal validation for speed
  
  # Monitoring Settings
  track_performance: true            # Track immediate processing performance
  log_response_times: true           # Log response times for optimization
  alert_on_delays: true              # Alert if delays detected