# config/agent_config.yaml - FIXED VERSION
# EDR Agent Configuration - Fixed for Connection Issues

# ============================================================================
# AGENT CORE CONFIGURATION - FIXED
# ============================================================================
agent:
  name: "EDR-SecurityAgent-Fixed"
  version: "2.0.0-Fixed"
  environment: "production"
  
  # Immediate transmission settings
  immediate_transmission: true
  zero_delay_mode: true
  
  # Heartbeat and Communication - FIXED
  heartbeat_interval: 30                # Increased for stability
  heartbeat_timeout: 60                 # Increased timeout
  max_heartbeat_failures: 5             # Allow more failures before giving up
  
  # Event Processing - FIXED
  event_batch_size: 1                   # Send one event immediately
  event_queue_size: 100                 # Larger queue for offline mode
  max_memory_usage: 512                 # Adequate memory
  
  # Performance Settings - FIXED
  max_cpu_usage: 25
  auto_throttle: true                   # Enable throttling to prevent overload
  adaptive_polling: true                # Enable adaptive polling
  
  # Processing configuration
  immediate_processing: true
  immediate_send_threshold_ms: 100      # Allow 100ms for processing
  minimal_polling_interval_ms: 500     # 500ms polling for stability

# ============================================================================
# SERVER CONNECTION CONFIGURATION - FIXED
# ============================================================================
server:
  # Primary Server - FIXED to use localhost first
  host: "127.0.0.1"                    # CHANGED: Use localhost first
  port: 5000
  protocol: "http"
  base_url: "http://127.0.0.1:5000"
  
  # Fallback servers for auto-detection
  fallback_servers:
    - host: "localhost"
      port: 5000
      name: "Local Server"
    - host: "192.168.20.85"             # Original server as fallback
      port: 5000
      name: "Remote Server"
    - host: "127.0.0.1"
      port: 8000
      name: "Alt Port 8000"
    - host: "localhost"
      port: 3000
      name: "Alt Port 3000"
  
  # Authentication
  auth_token: "edr_agent_auth_2024"
  
  # FIXED: Connection Settings for better reliability
  timeout: 5                            # Reasonable timeout
  connect_timeout: 2                    # Fast connection timeout
  read_timeout: 3                       # Fast read timeout
  max_retries: 1                        # Minimal retries for fast failure detection
  retry_delay: 0.5                      # Fast retry
  
  # Connection optimization
  keep_alive: true
  connection_pool_size: 5               # Smaller pool for stability
  pool_maxsize: 5
  pool_block: false
  
  # Offline Mode Support - NEW
  offline_mode_enabled: true            # Enable offline mode
  offline_queue_size: 1000              # Store up to 1000 events offline
  auto_reconnect: true                  # Auto-reconnect when server comes online
  reconnect_interval: 30                # Check every 30 seconds
  
  # SSL/TLS Settings
  ssl_enabled: false
  ssl_verify: false

# ============================================================================
# DATA COLLECTION CONFIGURATION - FIXED
# ============================================================================
collection:
  enabled: true
  
  # Global Collection Settings - FIXED
  real_time_monitoring: true
  immediate_processing: true
  polling_interval: 1.0                 # 1 second polling for stability
  max_events_per_interval: 5            # Limit events per interval
  event_deduplication: true             # Enable deduplication to reduce noise
  
  # Event Types - All enabled
  collect_processes: true
  collect_files: true
  collect_network: true
  collect_registry: true
  collect_authentication: true
  collect_system_events: true
  
  # Process Monitoring - FIXED
  process_monitoring:
    immediate_detection: true
    polling_interval_ms: 1000           # 1 second polling
    monitor_creation: true
    monitor_termination: true
    monitor_modification: true
    collect_command_lines: true
    collect_hashes: false               # Disabled for performance
    monitor_child_processes: true
  
  # File Monitoring - FIXED
  file_monitoring:
    enabled: true
    immediate_detection: true
    polling_interval_ms: 2000           # 2 second polling for files
    paths_to_monitor:
      - "C:\\Users\\manhh\\Desktop"
      - "C:\\Users\\manhh\\Documents"
      - "C:\\Users\\manhh\\Downloads"
      - "C:\\Windows\\System32"
    file_extensions:
      - ".exe"
      - ".dll"
      - ".bat"
      - ".cmd"
      - ".ps1"
      - ".vbs"
      - ".js"
    max_file_size: 50MB                 # Reasonable file size limit
    collect_hashes: false               # Disabled for performance
    monitor_creation: true
    monitor_modification: true
    monitor_deletion: true
    monitor_access: false               # Disabled to reduce noise
  
  # Network Monitoring - FIXED
  network_monitoring:
    immediate_detection: true
    polling_interval_ms: 2000           # 2 second polling for network
    monitor_tcp: true
    monitor_udp: false                  # Disabled to reduce noise
    monitor_listening_ports: true
    monitor_established_connections: true
    monitor_outbound_only: false        # Monitor both directions
    analyze_patterns: false             # Disabled for performance
    max_connections_tracked: 50         # Reduced for performance
  
  # Registry Monitoring - FIXED
  registry_monitoring:
    immediate_detection: true
    polling_interval_ms: 5000           # 5 second polling (registry is slower)
    monitor_startup_keys: true
    real_time_monitoring: true
    critical_paths:
      - "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run"
      - "HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run"
      - "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\RunOnce"
      - "HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\RunOnce"
  
  # Authentication Monitoring - FIXED
  authentication_monitoring:
    immediate_detection: true
    polling_interval_ms: 3000           # 3 second polling for auth events
    monitor_logons: true
    monitor_failed_attempts: true
    failed_attempt_threshold: 5         # Allow more attempts before alerting
  
  # System Monitoring - FIXED
  system_monitoring:
    immediate_detection: true
    polling_interval_ms: 5000           # 5 second polling for system metrics
    monitor_cpu_usage: true
    monitor_memory_usage: true
    monitor_disk_usage: true
    monitor_performance: true
    cpu_threshold: 85                   # Alert when CPU > 85%
    memory_threshold: 85                # Alert when memory > 85%
    disk_threshold: 90                  # Alert when disk > 90%

# ============================================================================
# THREAT DETECTION CONFIGURATION - FIXED
# ============================================================================
detection:
  enabled: true
  immediate_detection: true
  
  # Detection Engines - FIXED
  local_rules_enabled: true
  behavioral_analysis: false           # Disabled for performance
  threat_intelligence: false          # Disabled for performance
  
  # Detection Thresholds - FIXED
  suspicious_threshold: 70             # Lower threshold for more detection
  malicious_threshold: 85              # Reasonable threshold
  alert_threshold: 75                  # Reasonable threshold
  
  # Response Actions
  send_alerts_immediately: true
  immediate_response: true

# ============================================================================
# LOGGING CONFIGURATION - FIXED
# ============================================================================
logging:
  level: "INFO"
  
  # Output Destinations
  console_enabled: true
  file_enabled: true
  
  # File Logging - FIXED
  log_directory: "logs"
  log_file_name: "edr_agent_fixed.log"
  max_file_size: "10MB"
  backup_count: 3
  
  # Log Settings
  log_format: "detailed"               # More detailed for debugging
  include_timestamps: true
  include_thread_info: false
  
  # Component-specific Logging - FIXED
  collectors_log_level: "INFO"
  communication_log_level: "INFO"
  detection_log_level: "INFO"
  offline_mode_log_level: "INFO"       # NEW: Offline mode logging

# ============================================================================
# PERFORMANCE OPTIMIZATION - FIXED
# ============================================================================
performance:
  # CPU Management - FIXED
  max_cpu_usage: 25                    # Reasonable CPU limit
  cpu_throttling: true                 # Enable throttling
  priority_class: "normal"             # Normal priority for stability
  
  # Memory Management - FIXED
  max_memory_usage: 512                # Adequate memory
  memory_optimization: true
  garbage_collection: true             # Enable GC for stability
  
  # I/O Optimization - FIXED
  async_processing: true
  batch_processing: false              # Disabled for immediate processing
  compression_enabled: false          # Disabled for performance
  buffer_size: 4096                    # Reasonable buffer size
  
  # Threading - FIXED
  max_worker_threads: 4                # Reasonable thread count
  thread_pool_size: 4
  async_event_processing: true
  
  # Caching - FIXED
  enable_caching: false                # Disabled for immediate processing
  immediate_mode_optimizations: true

# ============================================================================
# FILTERING CONFIGURATION - FIXED
# ============================================================================
filters:
  # Minimal Filtering for comprehensive monitoring
  exclude_system_processes: false     # Monitor all processes
  exclude_agent_activity: true        # Exclude self
  
  # Process Filtering - FIXED
  exclude_process_names:
    - "System"
    - "Registry"
    - "MemCompression"
  exclude_process_paths:
    - "C:\\Windows\\System32\\svchost.exe"
  
  # File Filtering - FIXED
  exclude_file_extensions:
    - ".tmp"
    - ".log"
    - ".cache"
  exclude_file_paths:
    - "C:\\Windows\\Temp"
    - "C:\\Users\\*/AppData/Local/Temp"
  
  # Network Filtering - FIXED
  exclude_loopback: false              # Monitor loopback for testing
  exclude_ports:
    - 135    # RPC
    - 445    # SMB
    - 139    # NetBIOS
  
  # Size Limits - FIXED
  max_file_size_mb: 100                # Reasonable file size limit
  max_command_line_length: 2048        # Adequate command line length
  max_registry_value_size: 1024        # Adequate registry value size

# ============================================================================
# ALERTING CONFIGURATION - FIXED
# ============================================================================
alerting:
  enabled: true
  immediate_alerting: true
  
  # Alert Levels - FIXED
  send_info_alerts: false              # Reduce noise
  send_low_alerts: true
  send_medium_alerts: true
  send_high_alerts: true
  send_critical_alerts: true
  
  # Alert Throttling - FIXED
  throttle_duplicate_alerts: true      # Enable throttling
  duplicate_window: 60                 # 1 minute window
  max_alerts_per_minute: 10            # Reasonable alert rate
  
  # Alert Delivery - FIXED
  immediate_delivery: true
  batch_delivery: false
  batch_interval: 0

# ============================================================================
# SECURITY NOTIFICATION CONFIGURATION - FIXED
# ============================================================================
security_notifications:
  enabled: true
  immediate_notifications: true
  
  # Display Settings
  show_on_screen: true
  position: "bottom-right"
  
  # Alert Filtering - FIXED
  show_low_alerts: false               # Reduce noise
  show_medium_alerts: true
  show_high_alerts: true
  show_critical_alerts: true
  
  # Notification Behavior - FIXED
  auto_dismiss_timeout: 15             # Reasonable timeout
  play_sound: true
  persistent_critical: true
  
  # Rate Limiting - FIXED
  max_security_alerts_per_minute: 5    # Reasonable rate
  duplicate_suppression_window: 30     # 30 second window
  
  # Priority-based Timeouts
  critical_alert_timeout: 60
  high_alert_timeout: 45
  medium_alert_timeout: 30
  low_alert_timeout: 15
  
  # Content Settings
  include_rule_name: true
  include_risk_score: true
  include_event_details: true
  max_description_length: 200
  
  # Advanced Features
  group_similar_alerts: true           # Group similar alerts
  escalation_enabled: true
  integration_mode: "immediate"

# ============================================================================
# MAINTENANCE AND UPDATES - FIXED
# ============================================================================
maintenance:
  # Automatic Updates
  auto_update_enabled: false           # Disabled for stability
  
  # Cleanup Tasks - FIXED
  cleanup_enabled: true                # Enable cleanup
  cleanup_interval: 3600               # Every hour
  
  # Data Retention - FIXED
  event_retention_days: 7              # Keep events for 7 days
  log_retention_days: 30               # Keep logs for 30 days
  offline_event_retention_days: 3      # Keep offline events for 3 days
  
  # Health Monitoring - FIXED
  health_check_interval: 60            # Check every minute
  send_health_reports: true
  health_report_interval: 300          # Every 5 minutes

# ============================================================================
# OFFLINE MODE CONFIGURATION - NEW
# ============================================================================
offline_mode:
  # Core Settings
  enabled: true                        # Enable offline mode support
  auto_enable: true                    # Auto-enable when server unavailable
  
  # Storage Settings
  max_events_stored: 1000              # Maximum events to store offline
  storage_path: "offline_data"         # Directory for offline storage
  compression_enabled: false          # Disable compression for performance
  
  # Reconnection Settings
  auto_reconnect: true                 # Auto-reconnect when server available
  reconnect_interval: 30               # Check every 30 seconds
  max_reconnect_attempts: 0            # Unlimited attempts
  
  # Event Management
  event_priority_order:                # Priority order for sending events
    - "Critical"
    - "High"
    - "Medium"
    - "Low"
    - "Info"
  
  # Cleanup Settings
  auto_cleanup: true                   # Auto-cleanup old offline events
  cleanup_interval: 3600               # Every hour
  max_storage_size_mb: 100             # Maximum storage size

# ============================================================================
# ERROR HANDLING CONFIGURATION - NEW
# ============================================================================
error_handling:
  # Connection Errors
  max_connection_retries: 3            # Maximum connection retries
  connection_retry_delay: 1            # Delay between retries (seconds)
  connection_timeout: 5                # Connection timeout (seconds)
  
  # Processing Errors
  max_processing_errors: 10            # Maximum processing errors before restart
  error_backoff_multiplier: 2          # Backoff multiplier for errors
  max_error_backoff: 60                # Maximum error backoff (seconds)
  
  # Recovery Settings
  auto_recovery: true                  # Enable auto-recovery
  recovery_check_interval: 60          # Check every minute
  restart_on_critical_error: false    # Don't restart on critical errors
  
  # Logging
  log_all_errors: true                 # Log all errors
  error_notification_enabled: true    # Show error notifications